### ISSUE TITLE
Anomaly/analysis cold pool discussion web article

### ISSUE THREAD

**Issue by EmilyMarkowitz-NOAA** [afsc-gap-products/survey-live-temperature-map#6]
**Tentative!** I'm just summarizing our email chain here with the ideas we brought up.  

**Goals:** 
- Make the current year temperature map easier to interpret with context on past temperatures at that location
- Promote the incredible work done in the {[coldpool](https://github.com/afsc-gap-products/coldpool)} package and in the cold pool tech memo

**Tasks:** [Drafting google doc](https://docs.google.com/document/d/1LXTJc17dDxBuIyxVYM8bUwTpGR740SiwnOn6cklhYDw/edit?usp=sharing)
- [ ] Develop generalizable text to provide context for what the cold pool is
- [ ] A description of what we thing this year's cold pool will look like and why
- [ ] What the implications of a changing cold pool are (i.e., how a temperature increase of X here will have a greater impact than a temperature increase of Y will have on there))
- [ ] Description of data caveats in text or maps/plots
  - Difference in day of year sampled at a given station causing extra noise in the anomaly plot. Note that there are timing effects not accounted for here (nor in the cold pool tech memo), but see the tech memo for more details on how this may influence the results
- [ ] Possible maps
  - Anomaly (current year - mean temperatures)
  - Standard deviation of anomaly
  - Mean temperatures from past years
  - Last year's temperatures (found in past articles)
- [ ]

**Comment by EmilyMarkowitz-NOAA** [comment]
Hi all - it is that time of year again!

I wanted to resurrect this github issue and gauge your (@Lewis-Barnett-NOAA, @sean-rohan-NOAA, and @NicoleCharriere-NOAA) interest in developing Bering Sea temperature anomaly and context content for this year. @liz-dawson-NOAA, @ChrisAnderson-NOAA, and I spoke with Duane and we think it would be great to develop a separate page for more descriptive discussion about the temperatures we share on our main survey progression and temperatures observed page (e.g., [2022 BS page](https://www.fisheries.noaa.gov/alaska/climate/near-real-time-temperatures-bering-sea-bottom-trawl-surveys-2022)). 

**Our tentitive timeline for this project:** 
- March week 1
  - Create & review GOA figures (if making them)
  - Check final EBS/NBS figures with Duane
  - Meet with Comms to confirm roll out plan
  - facebook/instagram/twitter?
  - Discuss new 508 needs
  - Begin drafting temperature pages
     - Agree upon general outline for anomaly article (if producing it)
- March week 2: 
  - Near-final drafts of articles are completed
- March week 3: 
  - GAP and Comms finalize the content and roll out plan
- April week 1: 
  - Comms team creates pages
  - Comms does back-end FTP work
  - Comms’ last chance for 508 suggestions/updates
- April week 2: 
  - Final opportunity to test scripts and FTP server connection
- April week 3: 
  - Pages are live
- May week 1
  - The survey begins, and page updates are active

**Action items:**
- [ ] Are you guys interested in meeting about and putting a plan together for this? If yes, @liz-dawson-NOAA can set up a time for us. 
- [ ] We have this [document](https://docs.google.com/document/d/14N0-obgxy0Koz76lS3A_wxLdmAyJninRnH4kxAj_kno/edit) we initially put together last year that could be a starting point for drafting this document. Feel free to start adding material there.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks @EmilyMarkowitz-NOAA I think the nascent document looks like the right set of figures. I'm happy to help adapt some of the context and descriptions from the coldpool tech memo to whatever we decide is suitable.
